### ISSUE TITLE
home assistant intergration 

### ISSUE THREAD

**Issue by troydangerfield** [sillyfrog/currentcost-mqtt#4]
Yep I understand this is an old setup, however my CC monitor is now dead and I have picked up a Netsmart wireless gateway which the Serial is not working.  Found your code and trying to understand what is needed to get this working.

1 - setup a local DNS to redirec the 3 web links to ... (do I need to setup a local web server? )
2 - install your code but where?

I do have a MQTT broker running on Home assistant 

Really looking forward to getting this backup and running.

Oh have a great day :)

**Comment by troydangerfield** [comment]
also where do I get the following?

API_KEY = 'TheAPIKeyIsHere000000000000000000000000000000000'
FEED_ID = '1234567890'

**Comment by sillyfrog** [comment]
It's been a _looooong_ time since I've looked at this...

Re the first comment:

1. Where ever your DHCP points to for DNS, you will need to be able to control the DNS server, and put in custom entries. This is typically your router, and depending on the router depends on if you can setup custom DNS entries. I run a Linux edge router and run a full DNS server, so it was easy for me, but not sure how it'll go for a typical home router.
2. This code just needs to run anywhere it can run 24x7 - if you're running HA, then I would suggest running on that same server, either in a docker container or just on the server itself, main thing is you'll need to be able to use port `80` - so it may require adding a second IP address to the server (if there is another HTTP server already) and running it on just the one IP address. 

The `API_KEY` and `FEED_ID` don't need to be changed, this is just required to keep the device happy, and that specific combination worked when I was reverse engineering the protocol.

Good luck!

**Comment by troydangerfield** [comment]
I understand that you have closed off this task... 

Anyway I have had no luck getting a web server running with flask on HAOS, so was trying to go a different way.  I have created a dir for the active file (eg /activate/946bf9b7ff985e76679f4646fb38dbc82b5d2235.csv) and in this file have the following
{
   "API_KEY":"TheAPIKeyIsHere000000000000000000000000000000000",
   "FEED_ID":"1234567890"
}

When I go to this page the browswer downloads the CSV file.. but I am still getting an error on the logs

[18/Oct/2024:16:16:34 +1030] "GET /activate/946bf9b7ff985e76679f4646fb38dbc82b5d2235.csv HTTP/1.1\n" 400 320

So I am just trying to build the pages static so it can process the active and then work on the API to pull in the data.

I have the DNS redirect happing, the web server working on PHP  (can not get Flask to work)  happy to setup a static page to process each request.  

Looking foward to any help you can give. 

Thanks
Troy.

**Comment by troydangerfield** [comment]
Just an update, I have had no luck so sad to say this project has gone to land fill.  I have jumped onto Tuya clamp system and it seems to be working well.
